name: SonarQube analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  static-code-analysis:
    name : Static Code Review by Sonar Cube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
#          host: ${{ secrets.SONARQUBE_HOST }}
          host: "https://sonarcloud.io"
          login: ${{ secrets.SONAR_TOKEN }}
          projectBaseDir: "src/"
          projectKey: "my-custom-project"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: SonarCloud Scan
#        run: ./gradlew app:sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}